import type { Metadata } from "next";
import { Inter } from "next/font/google";

//전역 css적용
import "@/app/style/module.reset.css";
import "@/app/style/module.common.css";
import "@/app/style/module.layout.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "J.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
